AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  corpRate-backend

  Sample SAM Template for corpRate-backend


Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    
    LoggingConfig:
      LogFormat: JSON
Resources:
# HttpApi
  CorpRateHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      Name: CorpRateHttpApi
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - POST
          - OPTIONS
          - GET
        AllowOrigins: 
          - https://www.corprate.xyz
        MaxAge: 300
      Auth:
        Authorizers:
          CognitoAuth:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              audience:
                - !Ref CorpRateAppClient
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws/${CorpRateUserPool}"
        DefaultAuthorizer: CognitoAuth
# DynamoDB Table
  CorpRateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CorpRateTable
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "GSI1PK"
          AttributeType: "S"
        - AttributeName: "GSI1SK"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: ReviewsByTime
          KeySchema:
            - AttributeName: "GSI1PK"
              KeyType: "HASH"
            - AttributeName: "GSI1SK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
            
# SubmitReviewFunction
  SubmitReviewFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: submitReview/
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: SubmitReviewFunction
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CorpRateTable
      Events:
        SubmitReviewApiEvent:
          Type: HttpApi 
          Properties:
            Path: /submit-review
            Method: POST
            ApiId: !Ref CorpRateHttpApi
            Auth:
              Authorizer: CognitoAuth
      Policies:
        - AmazonDynamoDBFullAccess
        
# GetCompanyReviewsFunction
  GetCompanyReviewsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: getCompanyReviews/
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: GetCompanyReviewsFunction
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CorpRateTable
      Events:
        GetLatestReviewsApiEvent:
          Type: HttpApi 
          Properties:
            Path: /companies/{companyName}/reviews
            Method: GET
            ApiId: !Ref CorpRateHttpApi
            Auth:
              Authorizer: CognitoAuth
      Policies:
        - AmazonDynamoDBReadOnlyAccess
  
  # Get all companies ratings function
  GetCompaniesRatingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getCompaniesRatings/
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: GetCompaniesRatingsFunction
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CorpRateTable
      Events:
        GetCompaniesRatingsApiEvent:
          Type: HttpApi
          Properties:
            Path: /companies
            Method: GET
            ApiId: !Ref CorpRateHttpApi
            Auth:
              Authorizer: CognitoAuth
      Policies: 
        - AmazonDynamoDBReadOnlyAccess
  # Get recent reviews Fuunction
  GetRecentReviewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getRecentReviews
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: GetRecentReviews
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CorpRateTable
          GSI_NAME: 'ReviewsByTime'
      Events:
        GetRecentReviewsApiEvent:
          Type: HttpApi
          Properties:
            Path: /reviews
            Method: GET
            ApiId: !Ref CorpRateHttpApi
            Auth:
              Authorizer: CognitoAuth
      Policies:
        - AmazonDynamoDBReadOnlyAccess
  # Like Review Function
  LikeReviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: likeReview/
      Handler: app.lambda_handler
      Runtime: python3.13
      FunctionName: LikeReviewFunction
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CorpRateTable
      Events:
        LikeReviewApiEvent:
          Type: HttpApi
          Properties:
            Path: /like-review
            Method: POST
            ApiId: !Ref CorpRateHttpApi
            Auth:
              Authorizer: CognitoAuth
      Policies:
        - AmazonDynamoDBFullAccess  
  # Cognito User Pool
  CorpRateUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: corpRate-user-pool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      DeletionProtection: ACTIVE
      Policies:
        PasswordPolicy:
          MinimumLength: 6
  # Cognito User pool client
  CorpRateAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 30
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - https://corprate.xyz/
        - https://corprate.xyz/oauth-callback
      ClientName: corpRate-app-client
      DefaultRedirectURI: https://corprate.xyz/
      IdTokenValidity: 30
      LogoutURLs:
        - https://corprate.xyz/                     
      PreventUserExistenceErrors: ENABLED
      ReadAttributes:
        - email
        - email_verified
      RefreshTokenValidity: 10
      SupportedIdentityProviders:
        - COGNITO
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      UserPoolId: !Ref CorpRateUserPool
  # Hosted UI Domain
  UserPoolHostedUIDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CorpRateUserPool
      Domain: "corprate-dev"
  
  


Outputs:
  
  CorpRateHttpApiUrl:
    Description: API Gateway endpoint URL for dev stage for corpRate-backend 
      function
    Value: !Sub "https://${CorpRateHttpApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
  CognitoUserPoolId:
    Value: !Ref CorpRateUserPool
    Export:
      Name: CorpRateUserPoolId
