AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend-corp-app

  Sample SAM Template for backend-corp-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  CorpRateHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      Name: CorpRateHttpApi
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins: 
          - http://localhost:5173
        MaxAge: 300

  CorpRateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CorpRateTable
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"    

  SubmitReviewFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: SubmitReviewFunction
      CodeUri: submit_review/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: CorpRateTable
      Events:
        SubmitReviewApiEvent:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /review
            Method: POST
            ApiId: !Ref CorpRateHttpApi


  GetReviewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetReviewsFunction
      CodeUri: get_reviews/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: CorpRateTable
      Events:
        ReviewGetApiEvent:
          Type: HttpApi
          Properties:
            Path: /review/{Company}
            Method: GET
            ApiId: !Ref CorpRateHttpApi

  
Outputs:
  ApiUrl:
   Description: "API Gateway endpoint URL"
   Value: !Sub "https://${CorpRateHttpApi}.execute-api.${AWS::Region}.amazonaws.com/dev"